export const citiesData = [
  {
    id: 1,
    name: 'Warszawa',
    temp: 20,
    condition: 'Słonecznie',
    icon: '☀️',
    rainChance: 5,
    rainAmount: 0,
    windSpeed: 12,
    windDir: 'NW',
    cloudiness: 10,
    forecast: [
      { day: 'Pon', temp: 22, icon: '☀️' },
      { day: 'Wt', temp: 21, icon: '⛅' },
      { day: 'Śr', temp: 19, icon: '🌧️' },
      { day: 'Czw', temp: 20, icon: '⛅' },
      { day: 'Pt', temp: 23, icon: '☀️' },
    ]
  },
  {
    id: 2,
    name: 'Kraków',
    temp: 18,
    condition: 'Częściowe zachmurzenie',
    icon: '⛅',
    rainChance: 15,
    rainAmount: 0.2,
    windSpeed: 8,
    windDir: 'S',
    cloudiness: 40,
    forecast: [
      { day: 'Pon', temp: 19, icon: '⛅' },
      { day: 'Wt', temp: 18, icon: '🌧️' },
      { day: 'Śr', temp: 17, icon: '🌧️' },
      { day: 'Czw', temp: 20, icon: '☀️' },
      { day: 'Pt', temp: 22, icon: '☀️' },
    ]
  },
  {
    id: 3,
    name: 'Wrocław',
    temp: 22,
    condition: 'Gorąco',
    icon: '🔥',
    rainChance: 0,
    rainAmount: 0,
    windSpeed: 10,
    windDir: 'W',
    cloudiness: 5,
    forecast: [
      { day: 'Pon', temp: 24, icon: '☀️' },
      { day: 'Wt', temp: 25, icon: '☀️' },
      { day: 'Śr', temp: 23, icon: '⛅' },
      { day: 'Czw', temp: 21, icon: '⛈️' },
      { day: 'Pt', temp: 20, icon: '⛅' },
    ]
  },
  {
    id: 4,
    name: 'Łódź',
    temp: 19,
    condition: 'Pochmurno',
    icon: '☁️',
    rainChance: 20,
    rainAmount: 0,
    windSpeed: 15,
    windDir: 'NE',
    cloudiness: 80,
    forecast: [
      { day: 'Pon', temp: 18, icon: '☁️' },
      { day: 'Wt', temp: 17, icon: '🌧️' },
      { day: 'Śr', temp: 19, icon: '⛅' },
      { day: 'Czw', temp: 20, icon: '☀️' },
      { day: 'Pt', temp: 21, icon: '☀️' },
    ]
  },
  {
    id: 5,
    name: 'Gdańsk',
    temp: 16,
    condition: 'Wietrznie',
    icon: '💨',
    rainChance: 30,
    rainAmount: 0.5,
    windSpeed: 35,
    windDir: 'N',
    cloudiness: 60,
    forecast: [
      { day: 'Pon', temp: 15, icon: '🌧️' },
      { day: 'Wt', temp: 16, icon: '⛅' },
      { day: 'Śr', temp: 16, icon: '💨' },
      { day: 'Czw', temp: 17, icon: '☀️' },
      { day: 'Pt', temp: 18, icon: '☀️' },
    ]
  },
  {
    id: 6,
    name: 'Poznań',
    temp: 21,
    condition: 'Słonecznie',
    icon: '☀️',
    rainChance: 10,
    rainAmount: 0,
    windSpeed: 14,
    windDir: 'SW',
    cloudiness: 15,
    forecast: [
      { day: 'Pon', temp: 22, icon: '☀️' },
      { day: 'Wt', temp: 23, icon: '☀️' },
      { day: 'Śr', temp: 20, icon: '⛅' },
      { day: 'Czw', temp: 19, icon: '🌧️' },
      { day: 'Pt', temp: 21, icon: '☀️' },
    ]
  },
  {
    id: 7,
    name: 'Szczecin',
    temp: 17,
    condition: 'Lekki deszcz',
    icon: '🌦️',
    rainChance: 60,
    rainAmount: 1.2,
    windSpeed: 20,
    windDir: 'NW',
    cloudiness: 90,
    forecast: [
      { day: 'Pon', temp: 16, icon: '🌧️' },
      { day: 'Wt', temp: 17, icon: '☁️' },
      { day: 'Śr', temp: 18, icon: '⛅' },
      { day: 'Czw', temp: 19, icon: '☀️' },
      { day: 'Pt', temp: 18, icon: '⛅' },
    ]
  },
  {
    id: 8,
    name: 'Lublin',
    temp: 18,
    condition: 'Mglisto',
    icon: '🌫️',
    rainChance: 10,
    rainAmount: 0,
    windSpeed: 5,
    windDir: 'E',
    cloudiness: 30,
    forecast: [
      { day: 'Pon', temp: 19, icon: '⛅' },
      { day: 'Wt', temp: 20, icon: '☀️' },
      { day: 'Śr', temp: 21, icon: '☀️' },
      { day: 'Czw', temp: 18, icon: '☁️' },
      { day: 'Pt', temp: 17, icon: '🌧️' },
    ]
  },
  {
    id: 9,
    name: 'Białystok',
    temp: 15,
    condition: 'Chłodno',
    icon: '❄️',
    rainChance: 40,
    rainAmount: 2.0,
    windSpeed: 18,
    windDir: 'NE',
    cloudiness: 100,
    forecast: [
      { day: 'Pon', temp: 14, icon: '🌧️' },
      { day: 'Wt', temp: 13, icon: '🌧️' },
      { day: 'Śr', temp: 15, icon: '☁️' },
      { day: 'Czw', temp: 16, icon: '⛅' },
      { day: 'Pt', temp: 17, icon: '☀️' },
    ]
  },
  {
    id: 10,
    name: 'Katowice',
    temp: 20,
    condition: 'Przejściowe burze',
    icon: '⛈️',
    rainChance: 80,
    rainAmount: 5.5,
    windSpeed: 25,
    windDir: 'S',
    cloudiness: 70,
    forecast: [
      { day: 'Pon', temp: 21, icon: '☀️' },
      { day: 'Wt', temp: 22, icon: '⛅' },
      { day: 'Śr', temp: 19, icon: '⛈️' },
      { day: 'Czw', temp: 18, icon: '🌧️' },
      { day: 'Pt', temp: 20, icon: '☀️' },
    ]
  }
];